### PR TITLE
Update AOCODAF405V3 default config 

### PR DESCRIPTION
**Pull request by ChenYang78256**
1.Serial port 1 Use GPS
2.Serial port 2 Use a receiver
3.The  features of LED_STRIP、OSD、GPS are enabled by default
4. The default GPS protocol is ublox by default
5. The receiver selects CRSF protocol by default
6. The default motor protocol is Dshot600 by default 7.Bluetooth and 9v switches are enabled by default 8.Use the User1 and User2 modes

### CODE REVIEW

**Comment by lida2003** [comment]
> 1.Serial port 1 Use GPS
> 2.Serial port 2 Use a receiver
> 3.The features of LED_STRIP、OSD、GPS are enabled by default
> 4. The default GPS protocol is ublox by default
> 5. The receiver selects CRSF protocol by default
> 6. The default motor protocol is Dshot600 by default 
> 7.Bluetooth and 9v switches are enabled by default 
> 8.Use the User1 and User2 modes

a) Self test requested with F405V3 V2(HW)
b) Change PR title: which target is trying to change?
c) Default features should be consistent with https://github.com/Aocoda-RC/unified-targets/pull/2/commits/f2a0bfab73daed7f8c12c9b5f2a9c24e2ff34ffc

---

1. Select GPS for serial port 1 and vtx for serial port 2
2. LED lights are turned on by default
3. The default gps protocol is ublox
4. The receiver selects crsf protocol by default
5. The default motor protocol is Dshot600
6. Add user2 mode,
7. Bluetooth and vx (9v) are enabled by default

**Review by lida2003 — COMMENTED** [review]
LGTM, self test needed, using F405V3 V2(HW)

**Comment by ChenYang78256** [comment]
> > 1.Serial port 1 Use GPS
> > 2.Serial port 2 Use a receiver
> > 3.The features of LED_STRIP、OSD、GPS are enabled by default
> > 4. The default GPS protocol is ublox by default
> > 5. The receiver selects CRSF protocol by default
> > 6. The default motor protocol is Dshot600 by default
> > 7.Bluetooth and 9v switches are enabled by default
> > 8.Use the User1 and User2 modes
> 
> a) Self test requested with F405V3 V2(HW) b) Change PR title: which target is trying to change? c) Default features should be consistent with [Aocoda-RC/unified-targets@f2a0bfa](https://github.com/Aocoda-RC/unified-targets/commit/f2a0bfab73daed7f8c12c9b5f2a9c24e2ff34ffc)
> 
> 1. Select GPS for serial port 1 and vtx for serial port 2
> 2. LED lights are turned on by default
> 3. The default gps protocol is ublox
> 4. The receiver selects crsf protocol by default
> 5. The default motor protocol is Dshot600
> 6. Add user2 mode,
> 7. Bluetooth and vx (9v) are enabled by default

Title has been modified.
add default TELEMETRY feature.

**Comment by ChenYang78256** [comment]
> LGTM, self test needed, using F405V3 V2(HW)

No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.

**Comment by ChenYang78256** [comment]
> > LGTM, self test needed, using F405V3 V2(HW)
> 
> No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.

Except for this question,other features of F405V3 Flash V2 self test passed.

**Review by lida2003 — APPROVED** [review]
LGTM

**Pull request merged**
