### PR TITLE
Add CAM1/CAM2 support for AOCODAF405V3 

### PR DESCRIPTION
**Pull request by ChenYang78256**
1.Serial port 1 Use GPS
2.Serial port 2 Use a receiver
3.The features of LED_STRIP、OSD、GPS are enabled by default
4. The default GPS protocol is ublox by default
5. The receiver selects CRSF protocol by default
6. The default motor protocol is Dshot600 by default  
7.Bluetooth and 9v switches are enabled by default  
8.Use the User1 and User2 mode，User3 mode
9.Add User3 mode. User3 mode Controls the switchover between cam1 and cam2

### CODE REVIEW

**Comment by ChenYang78256** [comment]
No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.

**Comment by ChenYang78256** [comment]
Except for this question,other features of F405V3 Flash V3 self test passed

**Comment by lida2003** [comment]
> No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.

Did you try `#define MSP_UART SERIAL_PORT_UART5` ?

**Comment by ChenYang78256** [comment]
> > No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.
> 
> Did you try `#define MSP_UART SERIAL_PORT_UART5` ?

I've tried. There's no problem

**Comment by lida2003** [comment]
> I've tried. There's no problem

That's Good. Did self tests all passed now?

**Comment by lida2003** [comment]
It seems 

> > > No way was found to turn on MSP for Bluetooth enabled serial port 5 by default, so it needs to be opened manually in the port page on the BF ground station.
> > 
> > 
> > Did you try `#define MSP_UART SERIAL_PORT_UART5` ?
> 
> I've tried. There's no problem

It seems the issue is solved else where https://github.com/Aocoda-RC/betaflight-config/pull/6

**Pull request merged**
